apiVersion: apps/v1
kind: Deployment

metadata:
  name: self-healing-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: self-healing-app

  template:
    metadata:
      labels:
        app: self-healing-app

    spec:
      containers:
      - name: self-healing-app
        image: tejaskalal/self-healing-app:v1

        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

